### PR TITLE
[bug] can not compile on mac for the error of the endian.h

### PR DESCRIPTION
**Pull request by snowyu**
the endian.h's file in OSX should be:

* `machine/endian.h`

### CODE REVIEW

**Comment by mdoege** [comment]
Thanks for reporting! Does this also affect Yosemite? Neoscetic does his nightly builds on Mavericks I think and those seem to be fine.

Maybe you could also start a pull request at minetest/minetest. Since the nightly OS X builds are available, my build script probably is not used much anymore. Even I haven't used it in a while.

**Comment by snowyu** [comment]
yes, it is. ok already pr at minetest. your build script is still useful :)

**Comment by neoascetic** [comment]
For reference: minetest/minetest#2627

**Comment by neoascetic** [comment]
@mdoege can you prove that otherwise builds are broken, please?

**Comment by mdoege** [comment]
@neoascetic Your nightly builds work fine for me on Yosemite, so @snowyu needs to prove something is broken, not I.

**Comment by neoascetic** [comment]
Cannot reproduce on Yosemite.

**Comment by snowyu** [comment]
* endian.h is added after Sun Nov 16 21:52:24 2014 on minetest.
* do not use the native endian if no HAVE_ENDIAN_H defined.
* youe include_path should have an endian.h file.

**Pull request closed without merging**
